apiVersion: v1
kind: Config
clusters:
- name: k-test
  cluster:
    server: https://10.171.120.150:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQU1lVWo0KzRmNVpxWU9CUm9MWmF3RTR3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlNekE1TVRJeU1UQXlNakphRncwek16QTVNRGt5TVRBeQpNakphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVNLdlJKZ0JudXdlNURxelpkYnRFQkYweGxQc2o5RzZ6QkhDSXB3Q3YvVjlrQU45cThTbmp0clpjdXAKVVBScFBVWC9UWDlGaFhCNGNUTFQ2VmtRVk5qa28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGTUVYSThSZTRvUXJUVDkwNFJob21qNlNldzRqTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUNlQ1RRMUcKQjMxeWhvbnN1Q0VsczVNV09qelBpQ3NhckRlclJFK3dwRzNFQWlFQThVQTdvSS9nNzhzbm5kNDBaK3lmL2tRNQpHeXVKN0g0NXhQa1Z5T1I2YkFJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
users:
- name: admin@k-test
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoVENDQVN1Z0F3SUJBZ0lSQU41SVgzck53Q2ZXUlZmUldzTCs5MkV3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlNekE1TVRNeE9ESTBOVGRhRncwek16QTVNVEF4T0RJMApOVGRhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxjeVBTRXhwTnBoSWJDbjdmejh4RXVlM3FIRlArOVQKd0JUa3ZTaEoyTjJWZ0pwRGxpcmVWK3Ezd2lpWmxya3pBOXZIdmN4bmNsVmFjRjNjNm1nVnBSR2pTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlRCCkZ5UEVYdUtFSzAwL2RPRVlhSm8ra25zT0l6QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQkZHT1RXK3k4cE14OUwKblVzQ2hWcWhxM3U2bXFYOFlKZ1htUktmVC9zUEZRSWhBSm9KYnFOS3lnTG5KaWFoWktLSmFuV3NobXZXMHdiUQo2aThxTitJTHRZWksKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU16K2hicEZrdENaemc1R1N5WDNnaGM0dU1QKzJLUjBrYlRKWFI5T3JCcEpvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdHpJOUlUR2sybUVoc0tmdC9QekVTNTdlb2NVLzcxUEFGT1M5S0VuWTNaV0Fta09XS3Q1WAo2cmZDS0ptV3VUTUQyOGU5ekdkeVZWcHdYZHpxYUJXbEVRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
contexts:
- context:
    cluster: k-test
    namespace: default
    user: admin@k-test
  name: admin@k-test
current-context: admin@k-test
