kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: machine.talos.xfix.org
  labels:
    app: talos-operator
spec:
  group: talos.xfix.org
  names:
    plural: machine
    singular: machines
    kind: Machine
    listKind: MachineList
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: Server is the Schema for the servers API.
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: ServerSpec defines the desired state of Server.
              type: object
              required:
                - host
                - config
                - bootstrap
              properties:
                host:
                  type: string
                config:
                  type: string
                bootstrap:
                  type: boolean
                protected:
                  type: boolean
                  default: false
                params:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      value:
                        type: string
            status:
              type: object
              properties:
                status:
                  type: string
                bootstrapped:
                  type: boolean
                confighash:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.status
        - name: Config
          type: string
          jsonPath: .spec.config
        - name: Protected
          type: string
          jsonPath: .spec.protected
  conversion:
    strategy: None
