{{- range $template, $templateData := $.Values.cluster.templates }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "talos-%s-%s" $.Values.cluster.name $template }}
  labels:
    talos/secret-type: machineconfig
immutable: false
type: Opaque
data:
  kubeconfig: "dsds"
  talosconfig: {{ include "talosconfig" $.Values | b64enc }}
  machineconfig: {{ tpl (index $.Values.templates $templateData.template) (dict "Values" $.Values "Template" $.Template "cluster" $.Values.cluster "template" $templateData) | b64enc }}
---
{{- end }}
