{{- range $template, $templateData := $.Values.cluster.templates }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "talos-%s-%s" $.Values.cluster.name $template }}
immutable: false
type: Opaque
stringData:
  talos-config: "dsds"
  machine-config: {{ include $templateData.template (dict "cluster" $.Values.cluster "template" $templateData ) | toYaml | nindent 4 }}
---
{{- end }}
