{{- range $template, $templateData := $.Values.cluster.templates }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "talos-%s-%s" $.Values.cluster.name $template }}
immutable: false
type: Opaque
data:
  talos-config: {{ include "talosconfig" $.Values | b64enc }}
  machine-config: {{ tpl (index $.Values.templates $templateData.template) (dict "Values" $.Values "Template" $.Template "cluster" $.Values.cluster "template" $templateData) | b64enc }}
---
{{- end }}
